sudo: required
dist: trusty

language: python

# Use 'chef-stable-trusty' to install the stable release of the ChefDK
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.2.0.0

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/bin/chef gem install kitchen-docker
  - /opt/chefdk/bin/chef gem install kitchen-ansible
  - ansible-galaxy install -r requirements.yml


script:
  - /opt/chefdk/bin/kitchen --version
  - /opt/chefdk/bin/kitchen test
