sudo: required
dist: trusty

language: python

# Use 'chef-stable-trusty' to install the stable release of the ChefDK
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

script:
  - /opt/chefdk/bin/kitchen --version
