---
nginx_cdn_http_port: 80
nginx_cdn_https_port: 443
nginx_cdn_upstream_list:
  - server us-pro-host01.ext.cabify.com:443;
  - server us-pro-host02.ext.cabify.com:443;
  - server us-pro-host03.ext.cabify.com:443;
nginx_cdn_cache_file_formats:
  - ico
  - js
  - css
  - png
  - gif
  - jpe?g
  - swf
  - txt
  - html?
  - htc
nginx_cdn_proxy_next_upstream:
  - error
  - timeout
  - invalid_header
  - http_500
  - updating
nginx_cdn_http_default_params:
  - sendfile "on"
  - tcp_nopush "on"
  - tcp_nodelay "on"
  - keepalive_timeout "65"
  - access_log "{{nginx_log_dir}}/access.log"
  - "error_log {{nginx_log_dir}}/error.log {{nginx_error_log_level}}"
  - server_tokens off
  - types_hash_max_size 2048
nginx_http_params: "{{ nginx_cdn_http_default_params }}"
nginx_cdn_cache_path: /tmp/nginx-cache
nginx_cdn_proxy_cache_path_options:
  - "{{nginx_cdn_cache_path}}"
  - levels=1:2
  - keys_zone=cache:10m
  - inactive=30s
  - use_temp_path=off
